### PR TITLE
Tweak Python binding

### PR DESCRIPTION
**Pull request by messense**
* The first commit changes the import name from `minijinja_py` to `minijinja` and move the extension module to `minijinja._lowlevel`
* The second commit upgrades pyo3 to 0.18.0

### CODE REVIEW

File: minijinja-py/src/environment.rs [hunk 1]
```diff
@@ -12,15 +12,16 @@ use crate::typeconv::{
...
 pub struct Environment {
     inner: Mutex<minijinja::Environment<'static>>,
 }
 
 #[pymethods]
 impl Environment {
     #[new]
-    fn py_new() -> PyResult<Self> {
+    #[pyo3(signature = (**_kwargs))]
+    fn py_new(_kwargs: Option<&PyDict>) -> PyResult<Self> {
```
Comment (messense) [inline minijinja-py/src/environment.rs:24]: I had to add this `_kwargs: Option<&PyDict>` to make it work on Python 3.11, otherwise

```bash
$ python hello.py
Traceback (most recent call last):
  File "/Users/messense/Projects/minijinja/minijinja-py/hello.py", line 20, in <module>
    env = Environment(templates={
          ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Environment.__new__() got an unexpected keyword argument 'templates'
```

I'm not sure why, maybe @davidhewitt can shed some light?

Comment (messense) [reply minijinja-py/src/environment.rs:24]: Add a `__new__` that ignores the extra arguments to `minijinja.Environment` also works

```python
class Environment(_lowlevel.Environment):
    """Represents a MiniJinja environment"""
    def __new__(cls, *args, **kwargs):
        return super().__new__(cls)
```

Comment (davidhewitt) [reply minijinja-py/src/environment.rs]: It's from upgrading PyO3 to 0.18, there was a bug where new which takes no arguments would not error if arguments are passed. I can see it might be subtly annoying in inheritance cases like this!

**Comment by mitsuhiko** [comment]
Thanks. Already wanted to do some of those changes myself.
