### ISSUE TITLE
Breaking change of API between 1.19.1 and 1.20

### ISSUE THREAD

**Issue by chilabot** [mitsuhiko/minijinja#112]
## Description

The 'filters::Filter' changed its API between these versions, you should increment the mayor.

## Reproduction steps

This code works in 1.19.1 

```rust
struct Test {}

impl minijinja::filters::Filter<String, String, ()> for Test
{
    fn apply_to(&self, _state: &minijinja::State, _value: String, _args: ()) -> Result<String, minijinja::Error>
    {
        Ok("".to_string())
    }
}
```
But fails in 1.20
```
error[E0053]: method `apply_to` has an incompatible type for trait
  --> src/filters.rs:24:81
   |
24 |     fn apply_to(&self, _state: &minijinja::State, _value: String, _args: ()) -> Result<String, minijinja::Error>
   |                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                                                                 |
   |                                                                                 expected struct `std::string::String`, found enum `Result`
   |                                                                                 help: change the output type to match the trait: `std::string::String`
   |
   = note: expected fn pointer `fn(&filters::Test, &minijinja::State<'_, '_>, std::string::String, ()) -> std::string::String`
              found fn pointer `fn(&filters::Test, &minijinja::State<'_, '_>, std::string::String, ()) -> Result<std::string::String, minijinja::Error>`

error: aborting due to 2 previous errors
```

Additional helpful information:

- Version of rustc: 1.63.0 (4b91a6ea7 2022-08-08)
- Operating system and version: Ubuntu 20.04

## What did you expect

Should work because the mayor is the same (SemVer).

**Comment by mitsuhiko** [comment]
MiniJinja does not have a 1.x release yet, just a 0.x release so from 0.19 to 0.20 breakage is allowed:

> 0.x and 0.x+1 are not considered compatible, but 1.x and 1.x+1 are.

Specifically about your issue here: I did not intend the `Filter` trait to be public and I am trying to seal it up for the next version to avoid implementing it. Is there a specific reason you are trying to implement it rather than using functions?

**Comment by chilabot** [comment]
Oh sorry I got confused.

I implement Filter because I need data to be stored inside, and I tried a closure but didn't work.

**Comment by mitsuhiko** [comment]
@chilabot could you share that filter with me? Once I'm sealing up the trait a manual implementation won't work any more and then I have to ensure that is a reasonable migration path for this.

**Comment by chilabot** [comment]
```rust

pub struct NumFormat
{
    formatter: common::num_format::NumFormat
}

impl minijinja::filters::Filter<String, Result<String, minijinja::Error>, ()> for NumFormat
{
    fn apply_to(&self, _state: &minijinja::State, value: String, _args: ()) -> Result<String, minijinja::Error>
    {
        match self.formatter.format_num(&value)
        {
            Ok(value) => Ok(value),
            Err(error) => Err(minijinja::Error::new(minijinja::ErrorKind::SyntaxError, error))
        }
    }
}
.
.
.
ret.env.add_filter("numFormat", super::filters::NumFormat::new(common::num_format::NumFormat::new
(
    thousands_sep.to_string(),
    decimals_sep.to_string()
)));

```
The 'thousands_sep' and the 'decimals_sep' would go into the closure. Does 'add_filter' work with closures? Maybe I'm missing something. I'm fairly new in Rust.

**Comment by mitsuhiko** [comment]
Yes, you can do this with just closures. The most trivial way in which you can make this work is something like this:

```rust
let format = NumFormat::new(NumFormat::new(
    thousands_sep.to_string(),
    decimals_sep.to_string()
)));
env.add_filter(
    "numFormat",
    (move || {
        move |_state: &State, value: String| -> Result<String, Error> {
            format.format_num(&value).map_err(|err| {
                Error::new(ErrorKind::SyntaxError, "failed to format number").with_source(err)
            })
        }
    })(),
);
```

You just need to ensure that you use `move` for both closures.

**Comment by chilabot** [comment]
Excellent. I tried it and works, the problem was that I needed to set the types of the parameters 'state' and 'value'. 

Question: why the double closure? I tried with just one and works:

```rust
ret.env.add_filter
(
    "numFormat",
    move |_state: &minijinja::State, value: String| -> Result<String, minijinja::Error>
    {
        num_format.format_num(&value).map_err(|err|
        {
            minijinja::Error::new
            (
                minijinja::ErrorKind::SyntaxError,
                format!("failed to format number: {err}")
            )
        })
    }
);
```

**Comment by mitsuhiko** [comment]
The double closure is unnecessary. I just wanted to demonstrate how you can create a filter from another function. Going to close this as resolved.
