### ISSUE TITLE
Living on HEAD requires a bump of ahash dependency because of stdsimd feature. ahash 0.8.11 is ok.

### ISSUE THREAD

**Issue by gl-yziquel** [mitsuhiko/minijinja#573]
## Description

After an upgrade of rust, minijinja does not compile on HEAD because the ahash 0.8.3 dependency needs the feature stdsimd, which is not known.

```console
error[E0635]: unknown feature `stdsimd`
```

## Reproduction steps

Unclear how to reproduce. Do `cargo build`...

- Version of minijinja: 2.2.0. git SHA: 96dde1ec290b774fbbf088b7e9147315b080fe6c
- Version of rustc: rustc 1.83.0-nightly (bd53aa3bf 2024-09-02)
- Operating system and version: Ubuntu 24.04.1 LTS

## What did you expect

I would have expected a successful build.

## Workarounds:

Removing Cargo.lock and doing cargo build works fine. A bump of the ahash version somewhere between 0.8.3 and 0.8.11 should fix it.

**Comment by mitsuhiko** [comment]
I cannot reproduce this for some reason.  Can you please share the complete output?  `ahash` is only used by an example so I would assume this would not break minijinja.

**Comment by gl-yziquel** [comment]
@mitsuhiko 

Well, I do not know what kind of "complete output" you want.

```console
mini-me@virtucon ~/h/c/minijinja (main)> cargo build
   Compiling parse-zoneinfo v0.3.0
   Compiling serde_derive v1.0.204
   Compiling thiserror-impl v1.0.38
   Compiling tokio-macros v2.3.0
   Compiling rand_chacha v0.3.1
   Compiling proc-quote v0.4.0
   Compiling globset v0.4.10
   Compiling clap v4.3.22
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling pyo3-ffi v0.21.2
   Compiling pyo3-macros-backend v0.21.2
   Compiling sha1 v0.10.5
   Compiling pyo3 v0.21.2
   Compiling derive_more v0.99.17
   Compiling rustix v0.36.7
   Compiling askama_parser v0.2.1
   Compiling ahash v0.8.3
   Compiling base64 v0.21.2
   Compiling ciborium-io v0.2.1
   Compiling winnow v0.5.14
   Compiling deunicode v0.4.3
   Compiling anyhow v1.0.75
   Compiling fastrand v2.1.0
   Compiling argh_shared v0.1.10
   Compiling httpdate v1.0.2
   Compiling base64 v0.22.1
   Compiling notify v5.0.0
   Compiling serde_yml v0.0.10
   Compiling radix_trie v0.2.1
   Compiling embedding v0.1.0 (/home/mini-me/home/cellar/minijinja/examples/embedding)
   Compiling yaml-rust v0.4.5
   Compiling fancy-regex v0.11.0
   Compiling clap_mangen v0.2.22
   Compiling portable-atomic v1.6.0
   Compiling ciborium-ll v0.2.1
error[E0635]: unknown feature `stdsimd`
  --> /home/mini-me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.3/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

   Compiling liquid-derive v0.26.1
   Compiling argh_derive v0.1.10
   Compiling slug v0.1.4
   Compiling rand v0.8.5
   Compiling tempfile v3.10.1
   Compiling unic-segment v0.9.0
   Compiling humansize v2.1.3
For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by mitsuhiko** [comment]
I think the problem here might be that you are using nightly and you're trying to compile the entire workspace.  The workspace contains a lot of examples, nothing of which is tested against nightly.  If you compile minijinja itself `cargo build -p minijinja` or the cli `cargo build -p minijinja-cli` I would assume the build succeeds.

**Comment by gl-yziquel** [comment]
@mitsuhiko

You're absolutely right.

I do expect, though, that the whole workspace builds when pushing the repo in my continuous build system.

Anyway. Do as you wish.
